/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    About: (typeof import('./src/components/About.vue'))['default']
    NAlert: (typeof import('naive-ui'))['NAlert']
    NAutoComplete: (typeof import('naive-ui'))['NAutoComplete']
    NAvatar: (typeof import('naive-ui'))['NAvatar']
    NButton: (typeof import('naive-ui'))['NButton']
    NCard: (typeof import('naive-ui'))['NCard']
    NCol: (typeof import('naive-ui'))['NCol']
    NConfigProvider: (typeof import('naive-ui'))['NConfigProvider']
    NEllipsis: (typeof import('naive-ui'))['NEllipsis']
    NForm: (typeof import('naive-ui'))['NForm']
    NFormItem: (typeof import('naive-ui'))['NFormItem']
    NGradientText: (typeof import('naive-ui'))['NGradientText']
    NH3: (typeof import('naive-ui'))['NH3']
    NIcon: (typeof import('naive-ui'))['NIcon']
    NList: (typeof import('naive-ui'))['NList']
    NListItem: (typeof import('naive-ui'))['NListItem']
    NMessageProvider: (typeof import('naive-ui'))['NMessageProvider']
    NRow: (typeof import('naive-ui'))['NRow']
    NScrollbar: (typeof import('naive-ui'))['NScrollbar']
    NSpace: (typeof import('naive-ui'))['NSpace']
    NTabPane: (typeof import('naive-ui'))['NTabPane']
    NTabs: (typeof import('naive-ui'))['NTabs']
    NTag: (typeof import('naive-ui'))['NTag']
    NThing: (typeof import('naive-ui'))['NThing']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
    SouDanQu: (typeof import('./src/components/SouDanQu.vue'))['default']
    SouSongList: (typeof import('./src/components/SouSongList.vue'))['default']
    Titlebar: (typeof import('./src/components/titlebar.vue'))['default']
    Versions: (typeof import('./src/components/Versions.vue'))['default']
  }
}
