name: Build SparkMusic

on:
  push:
    tags:
      - v*.*.*
  workflow_dispatch:
jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: 检查Git仓库
        uses: actions/checkout@v3

      - name: 安装 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: 安装依赖
        run: npm install

      - name: 打包Linux版本
        if: matrix.os == 'ubuntu-latest'
        run: npm run build:linux

      - name: 打包MacOS版本
        if: matrix.os == 'macos-latest'
        run: npm run build:mac

      - name: 打包Windows版本
        if: matrix.os == 'windows-latest'
        run: npm run build:win

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            dist/*.exe
            dist/*.zip
            dist/*.dmg
            dist/*.AppImage
            dist/*.snap
            dist/*.deb
            dist/*.rpm
            dist/*.tar.gz
            dist/*.yml
            dist/*.blockmap
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
